config/routes.rb
Rails.application.routes.draw do
  root to: 'courses#index'
  get 'about', to: 'pages#about'
  resources :courses, except: [:index]
  resources :students
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'login', to: 'sessions#destroy'
  post 'course_enroll', to: 'student_courses#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  validates :short_name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 10}
  validates :name, presence: true, length: { minimum: 5, maximum: 50}
  validates :description, presence: true, length: { minimum: 5, maximum: 300 }
  has_many :student_courses
  has_many :students, through: :student_courses
end

app/models/student.rb
class Student < ApplicationRecord 
  has_secure_password
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { minimum: 5, maximum:50 }
  validates :email, presence: true, uniqueness: { case_sensitive: false },
                    length: { minimum: 5, maximum: 105 },
                    format: { with: URI::MailTo::EMAIL_REGEXP }
  has_many :student_courses
  has_many :courses, through: :student_courses
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :student 
  belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_user
  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= Student.find(session[:student_id]) if session[:student_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user 
    if !logged_in?
      flash[:notice] = "You must be logged in to perform that action"
      redirect_to login_path 
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :require_user

  def index 
    @courses = Course.all
  end

  def new 
  end

  def create 
  end

  def edit 
  end

  def update 
  end 

  def destroy 
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :require_user
  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_user, only: [:new, :create]
  def new 
  end

  def create
    student = Student.find_by(email: session_params[:email])
    if student && student.authenticate(session_params[:password])
      session[:student_id] = student.id
      flash[:notice] = "Successfully logged in"
      redirect_to student
    else
      flash.now[:notice] = "Something was wrong with your login information"
      render :new
    end
  end   

  def destroy
    session[:student_id] = nil 
    flash[:notice] = "Successfully logged out"
    redirect_to root_path
  end

  private 
  def session_params 
    params.require(:sessions)
  end
end

app/controllers/student_courses_controller.rb
class StudentCoursesController < ApplicationController
  def create
    course = Course.find(params[:course_id])
    unless current_user.courses.include?(course)
      current_user.courses << course
      flash[:notice] = "You have successfully enrolled in #{course.name}"
    else
      flash[:notice] = "Something was wrong with your enrollment"
    end
    redirect_to root_path
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  skip_before_action :require_user, only: [:new, :create]
  before_action :set_student, only: [:show, :edit, :update]
  before_action :require_same_student, only: [:edit, :update]

  def index 
    @students = Student.all
  end
  
  def show 
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save 
      flash[:notice] = "Successfully signed up"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @student.update(student_params)
      flash[:notice] = "You have successfully updated your profile"
      redirect_to @student
    else
      render :edit
    end
  end

  private 
  def student_params
    params.require(:student).permit(:name, :email, :password, :password_confirmation)
  end

  def set_student
    @student = Student.find(params[:id])
  end

  def require_same_student 
    if current_user != @student 
      flash[:notice] = "You can edit only your own profile"
      redirect_to edit_student_path @student
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper 
  def session_link
    if logged_in?
      link_to "logout", login_path, method: :delete
    else
      link_to "login", login_path
    end
  end
end

app/views/courses/_course.html.erb
<div class="col s12 m6">
  <div class="card blue-grey darken-1">
    <div class="card-content white-text">
      <span class="card-title"><%= course.short_name %>: <%= course.name %></span>
      <p><%= course.description %></p>
    </div>
    <div class="card-action">
      <% if logged_in? && !current_user.courses.include?(course) %>
        <%= link_to "Enroll", course_enroll_path(course_id: course), method: :post %>
      <% end %>
      <a href="#">Info</a>
    </div>
  </div>
</div>

app/views/courses/index.html.erb
<div class="row">
  <div class="s12">
    <h1 class="center-align">Course Listing</h1>
  </div>
</div>
<div class="row">
  <%= render @courses %>
</div>

app/views/layouts/_dropdown_account.html.erb
<ul id="account-dropdown" class="dropdown-content">
  <li><%= session_link %></li>
  <% if logged_in? %>
    <li><%= link_to "profile", current_user %></li>
  <% end %>
</ul>
<ul id="account-dropdown-mobile" class="dropdown-content">
  <li><%= session_link %></li>
  <% if logged_in? %>
    <li><%= link_to "profile", current_user %></li>
  <% end %>
</ul>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Tech University</h5>
        <p class="grey-text text-lighten-4">The future of development training</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Help</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Contact us</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2021 Copyright
    <a class="grey-text text-lighten-4 right" href="#!">About</a>
    </div>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |key, message| %>
  <div class="container">
      <div class="row sign-up-form">
        <div class="col s12 m12 l12">
          <div class="card-panel red lighten-2" id="fade-out-target">
            <span class="white-text">
              <%= message %>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<%= render "layouts/dropdown_account" %>
<nav>
  <div class="container">
    <div class="nav-wrapper">
      <%= link_to "Tech University", root_path, class: "brand-logo right" %>
      <a href="#" data-target="mobile-menu" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul id="nav-mobile" class="left hide-on-med-and-down">
        <li><%= link_to "Courses", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Enrollments", students_path %></li>
        <% end %>
        <li><a class="dropdown-trigger" data-target="account-dropdown">
          Account<i class="material-icons right">arrow_drop_down</i>
        </a></li>
      </ul>
    </div>
  </div>
</nav>
<ul class="sidenav" id="mobile-menu">
  <li><%= link_to "Courses", root_path %></li>
  <% if logged_in? %>
    <li><%= link_to "Enrollments", students_path %></li>
  <% end %>
  <li><a class="dropdown-trigger" data-target="account-dropdown-mobile">
    Account<i class="material-icons right">arrow_drop_down</i>
  </a></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tech University</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <main>
      <%= render "layouts/messages" %>
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
about

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="container">
    <div class="row sign-up-form">
      <div class="col s12 m12 l12">
        <div class="card-panel red lighten-2">
          <span class="white-text">
            <strong ><%= pluralize(object.errors.count, "error") %>
            prohibited profile from being created </strong>     
            <ul>
              <% object.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/students/_errors.html.erb
<% if @student.errors.any? %>
  <div class="container">
    <div class="row sign-up-form">
      <div class="col s12 m12 l12">
        <div class="card-panel red lighten-2">
          <span class="white-text">
            <strong ><%= pluralize(@student.errors.count, "error") %>
            prohibited profile from being created </strong>     
            <ul>
              <% @student.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/students/_form.html.erb
<%= render "shared/errors", object: @student %>
<div class="container">
  <div class="row center sign-up-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <h3 class="center-align"><%= @student.new_record?? "Sign Up" : "Edit profile" %></h3>
        <div class="row">
          <%= form_for @student, html: {class: "col s12"} do |f| %>
            <div class= "row">
              <div class="input-field col s12">
                <%= f.label :name %>
                <%= f.text_field :name, autofocus: true %>
              </div>
            </div>
            <div class= "row">
              <div class="input-field col s12">
                <%= f.label :email, class: "active" %>
                <%= f.text_field :email %>
              </div>
            </div>
            <div class= "row">
              <div class="input-field col s12">
                <%= f.label :password, class: "active" %>
                <%= f.password_field :password %>
              </div>
            </div>
            <div class= "row">
              <div class="input-field col s12">
                <%= f.label :password_confirmation, class: "active" %>
                <%= f.password_field :password_confirmation %>
              </div>
            </div>
            <%= f.button @student.new_record? ? 
                '<i class="material-icons right">send</i>Sign Up'.html_safe : 
                '<i class="material-icons right">send</i>Update profile'.html_safe, 
                class: "btn waves-effect waves-light right" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/_student.html.erb
<div class="col s12 m6">
  <div class="card blue-grey darken-1">
    <div class="card-content white-text">
      <span class="card-title"><%= "Name: #{student.name}" %> </span>
      <p><%= "Email: #{student.email}"%></p>
      <p><%= "Course enrollment" %></p>
    </div>
    <div class="card-action">
      <%= link_to "View profile", student %>
    </div>
  </div>
</div>

app/views/students/edit.html.erb
<%= render "form" %>

app/views/students/index.html.erb
<div class="row">
  <div class="s12">
    <h1 class="center-align">Course Listing</h1>
  </div>
</div>
<div class="row">
  <%= render @students %>
</div>

app/views/students/new.html.erb
<%= render "form" %>

app/views/students/show.html.erb
<div class="row sign-up-form">
  <div class="col s12 m6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%= "Name: #{@student.name}" %> </span>
        <p><%= "Email: #{@student.email}"%></p>
        <p>Course enrollments
          <% if @student.courses.empty? %>
            None
          <% else %>
            <ul>
              <% @student.courses.each do |course| %>
                <li> <%= course.name %> </li>
              <% end %>
            </ul>
          <% end %>
          </p>
      </div>
    </div>
    <%= link_to '<i class="material-icons right">create</i> Edit profile'.html_safe, edit_student_path(@student), 
                class: "waves-effect waves-light btn" if current_user==@student %>
  </div>
</div>